/**
 * Country and nationality constants
 */
export const NATIONALITIES = [
  "Afghan", "Albanian", "Algerian", "American", "Andorran", "Angolan", "Argentine", 
  "Armenian", "Australian", "Austrian", "Azerbaijani", "Bahamian", "Bahraini", 
  "Bangladeshi", "Barbadian", "Belarusian", "Belgian", "Belizean", "Beninese", 
  "Bhutanese", "Bolivian", "Bosnian", "Brazilian", "British", "Bruneian", 
  "Bulgarian", "Burkinabe", "Burmese", "Burundian", "Cambodian", "Cameroonian", 
  "Canadian", "Cape Verdean", "Central African", "Chadian", "Chilean", "Chinese", 
  "Colombian", "Comoran", "Congolese", "Costa Rican", "Croatian", "Cuban", 
  "Cypriot", "Czech", "Danish", "Djiboutian", "Dominican", "Dutch", "Ecuadorian", 
  "Egyptian", "Emirati", "English", "Equatorial Guinean", "Eritrean", "Estonian", 
  "Ethiopian", "Fijian", "Filipino", "Finnish", "French", "Gabonese", "Gambian", 
  "Georgian", "German", "Ghanaian", "Greek", "Grenadian", "Guatemalan", "Guinean", 
  "Guyanese", "Haitian", "Honduran", "Hungarian", "Icelandic", "Indian", 
  "Indonesian", "Iranian", "Iraqi", "Irish", "Israeli", "Italian", "Ivorian", 
  "Jamaican", "Japanese", "Jordanian", "Kazakh", "Kenyan", "Kuwaiti", "Kyrgyz", 
  "Laotian", "Latvian", "Lebanese", "Liberian", "Libyan", "Lithuanian", 
  "Luxembourgish", "Macedonian", "Malagasy", "Malawian", "Malaysian", "Maldivian", 
  "Malian", "Maltese", "Mauritanian", "Mauritian", "Mexican", "Moldovan", 
  "Monacan", "Mongolian", "Montenegrin", "Moroccan", "Mozambican", "Namibian", 
  "Nepalese", "New Zealand", "Nicaraguan", "Nigerian", "Nigerien", "North Korean", 
  "Norwegian", "Omani", "Pakistani", "Panamanian", "Papua New Guinean", 
  "Paraguayan", "Peruvian", "Polish", "Portuguese", "Qatari", "Romanian", 
  "Russian", "Rwandan", "Saint Lucian", "Salvadoran", "Samoan", "Saudi", 
  "Scottish", "Senegalese", "Serbian", "Seychellois", "Sierra Leonean", 
  "Singaporean", "Slovak", "Slovenian", "Somali", "South African", "South Korean", 
  "Spanish", "Sri Lankan", "Sudanese", "Surinamese", "Swazi", "Swedish", "Swiss", 
  "Syrian", "Taiwanese", "Tajik", "Tanzanian", "Thai", "Togolese", "Tongan", 
  "Trinidadian", "Tunisian", "Turkish", "Turkmen", "Ugandan", "Ukrainian", 
  "Uruguayan", "Uzbek", "Venezuelan", "Vietnamese", "Welsh", "Yemeni", "Zambian", 
  "Zimbabwean"
];

export const NIGERIAN_BANKS = [
  "Access Bank",
  "Carbon",
  "Citibank Nigeria",
  "Ecobank Nigeria",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "Guaranty Trust Bank (GTBank)",
  "Heritage Bank",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda Bank",
  "Moniepoint",
  "OPay",
  "PalmPay",
  "Parallex Bank",
  "Polaris Bank",
  "Providus Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "Union Bank",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "Wema Bank",
  "Zenith Bank",
];
